version: '3.8'

services:
  appjc:
    imagen: ghcr.io/yaviracjorge/holaflask
    ports:
      - target: 5000
        published: 7000
        protocol: tcp
        mode: host
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.appjc.entrypoints=http"
        - "traefik.http.routers.appjc.rule=Host(`appjc.byronrm.com`)"
        - "traefik.http.middlewares.appjc-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.appjc.middlewares=portainer-https-redirect"
        - "traefik.http.routers.appjc-secure.entrypoints=https"
        - "traefik.http.routers.appjc-secure.rule=Host(`appjc.byronrm.com`)"
        - "traefik.http.routers.appjc-secure.tls=true"
        - "traefik.http.routers.appjc-secure.tls.certresolver=http"
        - "traefik.http.routers.appjc-secure.service=appjc"
        - "traefik.http.services.appjc.loadbalancer.server.port=7000"
        - "traefik.docker.network=traefik-public
network:
  traefik-public
    external: true 

